// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        (unknown)
// source: grpc/protos/core.proto

package org_dash_platform_dapi_v0

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoreVersion     uint32  `protobuf:"varint,1,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	ProtocolVersion uint32  `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Blocks          uint32  `protobuf:"varint,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	TimeOffset      uint32  `protobuf:"varint,4,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	Connections     uint32  `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	Proxy           string  `protobuf:"bytes,6,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Difficulty      float64 `protobuf:"fixed64,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Testnet         bool    `protobuf:"varint,8,opt,name=testnet,proto3" json:"testnet,omitempty"`
	RelayFee        float64 `protobuf:"fixed64,9,opt,name=relay_fee,json=relayFee,proto3" json:"relay_fee,omitempty"`
	Errors          string  `protobuf:"bytes,10,opt,name=errors,proto3" json:"errors,omitempty"`
	Network         string  `protobuf:"bytes,11,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetCoreVersion() uint32 {
	if x != nil {
		return x.CoreVersion
	}
	return 0
}

func (x *GetStatusResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GetStatusResponse) GetBlocks() uint32 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *GetStatusResponse) GetTimeOffset() uint32 {
	if x != nil {
		return x.TimeOffset
	}
	return 0
}

func (x *GetStatusResponse) GetConnections() uint32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *GetStatusResponse) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *GetStatusResponse) GetDifficulty() float64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GetStatusResponse) GetTestnet() bool {
	if x != nil {
		return x.Testnet
	}
	return false
}

func (x *GetStatusResponse) GetRelayFee() float64 {
	if x != nil {
		return x.RelayFee
	}
	return 0
}

func (x *GetStatusResponse) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

func (x *GetStatusResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type GetBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Block:
	//	*GetBlockRequest_Height
	//	*GetBlockRequest_Hash
	Block isGetBlockRequest_Block `protobuf_oneof:"block"`
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{2}
}

func (m *GetBlockRequest) GetBlock() isGetBlockRequest_Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (x *GetBlockRequest) GetHeight() uint32 {
	if x, ok := x.GetBlock().(*GetBlockRequest_Height); ok {
		return x.Height
	}
	return 0
}

func (x *GetBlockRequest) GetHash() string {
	if x, ok := x.GetBlock().(*GetBlockRequest_Hash); ok {
		return x.Hash
	}
	return ""
}

type isGetBlockRequest_Block interface {
	isGetBlockRequest_Block()
}

type GetBlockRequest_Height struct {
	Height uint32 `protobuf:"varint,1,opt,name=height,proto3,oneof"`
}

type GetBlockRequest_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

func (*GetBlockRequest_Height) isGetBlockRequest_Block() {}

func (*GetBlockRequest_Hash) isGetBlockRequest_Block() {}

type GetBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block []byte `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockResponse) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

type SendTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction   []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	AllowHighFees bool   `protobuf:"varint,2,opt,name=allow_high_fees,json=allowHighFees,proto3" json:"allow_high_fees,omitempty"`
	BypassLimits  bool   `protobuf:"varint,3,opt,name=bypass_limits,json=bypassLimits,proto3" json:"bypass_limits,omitempty"`
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{4}
}

func (x *SendTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SendTransactionRequest) GetAllowHighFees() bool {
	if x != nil {
		return x.AllowHighFees
	}
	return false
}

func (x *SendTransactionRequest) GetBypassLimits() bool {
	if x != nil {
		return x.BypassLimits
	}
	return false
}

type SendTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *SendTransactionResponse) Reset() {
	*x = SendTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionResponse) ProtoMessage() {}

func (x *SendTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{5}
}

func (x *SendTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionResponse) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type BlockHeadersWithChainLocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to FromBlock:
	//	*BlockHeadersWithChainLocksRequest_FromBlockHash
	//	*BlockHeadersWithChainLocksRequest_FromBlockHeight
	FromBlock isBlockHeadersWithChainLocksRequest_FromBlock `protobuf_oneof:"from_block"`
	Count     uint32                                        `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BlockHeadersWithChainLocksRequest) Reset() {
	*x = BlockHeadersWithChainLocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeadersWithChainLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeadersWithChainLocksRequest) ProtoMessage() {}

func (x *BlockHeadersWithChainLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeadersWithChainLocksRequest.ProtoReflect.Descriptor instead.
func (*BlockHeadersWithChainLocksRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{8}
}

func (m *BlockHeadersWithChainLocksRequest) GetFromBlock() isBlockHeadersWithChainLocksRequest_FromBlock {
	if m != nil {
		return m.FromBlock
	}
	return nil
}

func (x *BlockHeadersWithChainLocksRequest) GetFromBlockHash() []byte {
	if x, ok := x.GetFromBlock().(*BlockHeadersWithChainLocksRequest_FromBlockHash); ok {
		return x.FromBlockHash
	}
	return nil
}

func (x *BlockHeadersWithChainLocksRequest) GetFromBlockHeight() uint32 {
	if x, ok := x.GetFromBlock().(*BlockHeadersWithChainLocksRequest_FromBlockHeight); ok {
		return x.FromBlockHeight
	}
	return 0
}

func (x *BlockHeadersWithChainLocksRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type isBlockHeadersWithChainLocksRequest_FromBlock interface {
	isBlockHeadersWithChainLocksRequest_FromBlock()
}

type BlockHeadersWithChainLocksRequest_FromBlockHash struct {
	FromBlockHash []byte `protobuf:"bytes,1,opt,name=from_block_hash,json=fromBlockHash,proto3,oneof"`
}

type BlockHeadersWithChainLocksRequest_FromBlockHeight struct {
	FromBlockHeight uint32 `protobuf:"varint,2,opt,name=from_block_height,json=fromBlockHeight,proto3,oneof"`
}

func (*BlockHeadersWithChainLocksRequest_FromBlockHash) isBlockHeadersWithChainLocksRequest_FromBlock() {
}

func (*BlockHeadersWithChainLocksRequest_FromBlockHeight) isBlockHeadersWithChainLocksRequest_FromBlock() {
}

type BlockHeadersWithChainLocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Responses:
	//	*BlockHeadersWithChainLocksResponse_BlockHeaders
	//	*BlockHeadersWithChainLocksResponse_ChainLockSignatureMessages
	Responses isBlockHeadersWithChainLocksResponse_Responses `protobuf_oneof:"responses"`
}

func (x *BlockHeadersWithChainLocksResponse) Reset() {
	*x = BlockHeadersWithChainLocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeadersWithChainLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeadersWithChainLocksResponse) ProtoMessage() {}

func (x *BlockHeadersWithChainLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeadersWithChainLocksResponse.ProtoReflect.Descriptor instead.
func (*BlockHeadersWithChainLocksResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{9}
}

func (m *BlockHeadersWithChainLocksResponse) GetResponses() isBlockHeadersWithChainLocksResponse_Responses {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (x *BlockHeadersWithChainLocksResponse) GetBlockHeaders() *BlockHeaders {
	if x, ok := x.GetResponses().(*BlockHeadersWithChainLocksResponse_BlockHeaders); ok {
		return x.BlockHeaders
	}
	return nil
}

func (x *BlockHeadersWithChainLocksResponse) GetChainLockSignatureMessages() *ChainLockSignatureMessages {
	if x, ok := x.GetResponses().(*BlockHeadersWithChainLocksResponse_ChainLockSignatureMessages); ok {
		return x.ChainLockSignatureMessages
	}
	return nil
}

type isBlockHeadersWithChainLocksResponse_Responses interface {
	isBlockHeadersWithChainLocksResponse_Responses()
}

type BlockHeadersWithChainLocksResponse_BlockHeaders struct {
	BlockHeaders *BlockHeaders `protobuf:"bytes,1,opt,name=block_headers,json=blockHeaders,proto3,oneof"`
}

type BlockHeadersWithChainLocksResponse_ChainLockSignatureMessages struct {
	ChainLockSignatureMessages *ChainLockSignatureMessages `protobuf:"bytes,2,opt,name=chain_lock_signature_messages,json=chainLockSignatureMessages,proto3,oneof"`
}

func (*BlockHeadersWithChainLocksResponse_BlockHeaders) isBlockHeadersWithChainLocksResponse_Responses() {
}

func (*BlockHeadersWithChainLocksResponse_ChainLockSignatureMessages) isBlockHeadersWithChainLocksResponse_Responses() {
}

type BlockHeaders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers [][]byte `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *BlockHeaders) Reset() {
	*x = BlockHeaders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeaders) ProtoMessage() {}

func (x *BlockHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeaders.ProtoReflect.Descriptor instead.
func (*BlockHeaders) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{10}
}

func (x *BlockHeaders) GetHeaders() [][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ChainLockSignatureMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages [][]byte `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ChainLockSignatureMessages) Reset() {
	*x = ChainLockSignatureMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainLockSignatureMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainLockSignatureMessages) ProtoMessage() {}

func (x *ChainLockSignatureMessages) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainLockSignatureMessages.ProtoReflect.Descriptor instead.
func (*ChainLockSignatureMessages) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{11}
}

func (x *ChainLockSignatureMessages) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetEstimatedTransactionFeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks uint32 `protobuf:"varint,1,opt,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *GetEstimatedTransactionFeeRequest) Reset() {
	*x = GetEstimatedTransactionFeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEstimatedTransactionFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatedTransactionFeeRequest) ProtoMessage() {}

func (x *GetEstimatedTransactionFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatedTransactionFeeRequest.ProtoReflect.Descriptor instead.
func (*GetEstimatedTransactionFeeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{12}
}

func (x *GetEstimatedTransactionFeeRequest) GetBlocks() uint32 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

type GetEstimatedTransactionFeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee float64 `protobuf:"fixed64,1,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *GetEstimatedTransactionFeeResponse) Reset() {
	*x = GetEstimatedTransactionFeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_core_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEstimatedTransactionFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatedTransactionFeeResponse) ProtoMessage() {}

func (x *GetEstimatedTransactionFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_core_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatedTransactionFeeResponse.ProtoReflect.Descriptor instead.
func (*GetEstimatedTransactionFeeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_core_proto_rawDescGZIP(), []int{13}
}

func (x *GetEstimatedTransactionFeeResponse) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

var File_grpc_protos_core_proto protoreflect.FileDescriptor

var file_grpc_protos_core_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x30, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xdb, 0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x65, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74,
	0x65, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f,
	0x66, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x46, 0x65, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x42, 0x07, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x87, 0x01, 0x0a, 0x16,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x66, 0x65, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x48, 0x69, 0x67, 0x68, 0x46, 0x65, 0x65, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9f, 0x01, 0x0a,
	0x21, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74,
	0x68, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0d, 0x66,
	0x72, 0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2c, 0x0a, 0x11,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x0c, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0xfd,
	0x01, 0x0a, 0x22, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x57,
	0x69, 0x74, 0x68, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x7a, 0x0a, 0x1d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x6f,
	0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x48, 0x00, 0x52, 0x1a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x6b,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x42, 0x0b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x28,
	0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x38, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x22, 0x3b, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22,
	0x36, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x66, 0x65, 0x65, 0x32, 0x89, 0x06, 0x0a, 0x04, 0x43, 0x6f, 0x72, 0x65,
	0x12, 0x66, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2a, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a,
	0x0f, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x75, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x99,
	0x01, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x65, 0x12, 0x3c, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74,
	0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x46, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0xa6, 0x01, 0x0a, 0x25, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74,
	0x68, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_protos_core_proto_rawDescOnce sync.Once
	file_grpc_protos_core_proto_rawDescData = file_grpc_protos_core_proto_rawDesc
)

func file_grpc_protos_core_proto_rawDescGZIP() []byte {
	file_grpc_protos_core_proto_rawDescOnce.Do(func() {
		file_grpc_protos_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_protos_core_proto_rawDescData)
	})
	return file_grpc_protos_core_proto_rawDescData
}

var file_grpc_protos_core_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grpc_protos_core_proto_goTypes = []interface{}{
	(*GetStatusRequest)(nil),                   // 0: org.dash.platform.dapi.v0.GetStatusRequest
	(*GetStatusResponse)(nil),                  // 1: org.dash.platform.dapi.v0.GetStatusResponse
	(*GetBlockRequest)(nil),                    // 2: org.dash.platform.dapi.v0.GetBlockRequest
	(*GetBlockResponse)(nil),                   // 3: org.dash.platform.dapi.v0.GetBlockResponse
	(*SendTransactionRequest)(nil),             // 4: org.dash.platform.dapi.v0.SendTransactionRequest
	(*SendTransactionResponse)(nil),            // 5: org.dash.platform.dapi.v0.SendTransactionResponse
	(*GetTransactionRequest)(nil),              // 6: org.dash.platform.dapi.v0.GetTransactionRequest
	(*GetTransactionResponse)(nil),             // 7: org.dash.platform.dapi.v0.GetTransactionResponse
	(*BlockHeadersWithChainLocksRequest)(nil),  // 8: org.dash.platform.dapi.v0.BlockHeadersWithChainLocksRequest
	(*BlockHeadersWithChainLocksResponse)(nil), // 9: org.dash.platform.dapi.v0.BlockHeadersWithChainLocksResponse
	(*BlockHeaders)(nil),                       // 10: org.dash.platform.dapi.v0.BlockHeaders
	(*ChainLockSignatureMessages)(nil),         // 11: org.dash.platform.dapi.v0.ChainLockSignatureMessages
	(*GetEstimatedTransactionFeeRequest)(nil),  // 12: org.dash.platform.dapi.v0.GetEstimatedTransactionFeeRequest
	(*GetEstimatedTransactionFeeResponse)(nil), // 13: org.dash.platform.dapi.v0.GetEstimatedTransactionFeeResponse
}
var file_grpc_protos_core_proto_depIdxs = []int32{
	10, // 0: org.dash.platform.dapi.v0.BlockHeadersWithChainLocksResponse.block_headers:type_name -> org.dash.platform.dapi.v0.BlockHeaders
	11, // 1: org.dash.platform.dapi.v0.BlockHeadersWithChainLocksResponse.chain_lock_signature_messages:type_name -> org.dash.platform.dapi.v0.ChainLockSignatureMessages
	0,  // 2: org.dash.platform.dapi.v0.Core.getStatus:input_type -> org.dash.platform.dapi.v0.GetStatusRequest
	2,  // 3: org.dash.platform.dapi.v0.Core.getBlock:input_type -> org.dash.platform.dapi.v0.GetBlockRequest
	4,  // 4: org.dash.platform.dapi.v0.Core.sendTransaction:input_type -> org.dash.platform.dapi.v0.SendTransactionRequest
	6,  // 5: org.dash.platform.dapi.v0.Core.getTransaction:input_type -> org.dash.platform.dapi.v0.GetTransactionRequest
	12, // 6: org.dash.platform.dapi.v0.Core.getEstimatedTransactionFee:input_type -> org.dash.platform.dapi.v0.GetEstimatedTransactionFeeRequest
	8,  // 7: org.dash.platform.dapi.v0.Core.subscribeToBlockHeadersWithChainLocks:input_type -> org.dash.platform.dapi.v0.BlockHeadersWithChainLocksRequest
	1,  // 8: org.dash.platform.dapi.v0.Core.getStatus:output_type -> org.dash.platform.dapi.v0.GetStatusResponse
	3,  // 9: org.dash.platform.dapi.v0.Core.getBlock:output_type -> org.dash.platform.dapi.v0.GetBlockResponse
	5,  // 10: org.dash.platform.dapi.v0.Core.sendTransaction:output_type -> org.dash.platform.dapi.v0.SendTransactionResponse
	7,  // 11: org.dash.platform.dapi.v0.Core.getTransaction:output_type -> org.dash.platform.dapi.v0.GetTransactionResponse
	13, // 12: org.dash.platform.dapi.v0.Core.getEstimatedTransactionFee:output_type -> org.dash.platform.dapi.v0.GetEstimatedTransactionFeeResponse
	9,  // 13: org.dash.platform.dapi.v0.Core.subscribeToBlockHeadersWithChainLocks:output_type -> org.dash.platform.dapi.v0.BlockHeadersWithChainLocksResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_protos_core_proto_init() }
func file_grpc_protos_core_proto_init() {
	if File_grpc_protos_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_protos_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeadersWithChainLocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeadersWithChainLocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeaders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainLockSignatureMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEstimatedTransactionFeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_core_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEstimatedTransactionFeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_protos_core_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*GetBlockRequest_Height)(nil),
		(*GetBlockRequest_Hash)(nil),
	}
	file_grpc_protos_core_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*BlockHeadersWithChainLocksRequest_FromBlockHash)(nil),
		(*BlockHeadersWithChainLocksRequest_FromBlockHeight)(nil),
	}
	file_grpc_protos_core_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*BlockHeadersWithChainLocksResponse_BlockHeaders)(nil),
		(*BlockHeadersWithChainLocksResponse_ChainLockSignatureMessages)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_protos_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protos_core_proto_goTypes,
		DependencyIndexes: file_grpc_protos_core_proto_depIdxs,
		MessageInfos:      file_grpc_protos_core_proto_msgTypes,
	}.Build()
	File_grpc_protos_core_proto = out.File
	file_grpc_protos_core_proto_rawDesc = nil
	file_grpc_protos_core_proto_goTypes = nil
	file_grpc_protos_core_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoreClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	GetEstimatedTransactionFee(ctx context.Context, in *GetEstimatedTransactionFeeRequest, opts ...grpc.CallOption) (*GetEstimatedTransactionFeeResponse, error)
	SubscribeToBlockHeadersWithChainLocks(ctx context.Context, in *BlockHeadersWithChainLocksRequest, opts ...grpc.CallOption) (Core_SubscribeToBlockHeadersWithChainLocksClient, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Core/getStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Core/getBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Core/sendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Core/getTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetEstimatedTransactionFee(ctx context.Context, in *GetEstimatedTransactionFeeRequest, opts ...grpc.CallOption) (*GetEstimatedTransactionFeeResponse, error) {
	out := new(GetEstimatedTransactionFeeResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Core/getEstimatedTransactionFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) SubscribeToBlockHeadersWithChainLocks(ctx context.Context, in *BlockHeadersWithChainLocksRequest, opts ...grpc.CallOption) (Core_SubscribeToBlockHeadersWithChainLocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Core_serviceDesc.Streams[0], "/org.dash.platform.dapi.v0.Core/subscribeToBlockHeadersWithChainLocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreSubscribeToBlockHeadersWithChainLocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_SubscribeToBlockHeadersWithChainLocksClient interface {
	Recv() (*BlockHeadersWithChainLocksResponse, error)
	grpc.ClientStream
}

type coreSubscribeToBlockHeadersWithChainLocksClient struct {
	grpc.ClientStream
}

func (x *coreSubscribeToBlockHeadersWithChainLocksClient) Recv() (*BlockHeadersWithChainLocksResponse, error) {
	m := new(BlockHeadersWithChainLocksResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CoreServer is the server API for Core service.
type CoreServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	GetEstimatedTransactionFee(context.Context, *GetEstimatedTransactionFeeRequest) (*GetEstimatedTransactionFeeResponse, error)
	SubscribeToBlockHeadersWithChainLocks(*BlockHeadersWithChainLocksRequest, Core_SubscribeToBlockHeadersWithChainLocksServer) error
}

// UnimplementedCoreServer can be embedded to have forward compatible implementations.
type UnimplementedCoreServer struct {
}

func (*UnimplementedCoreServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedCoreServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (*UnimplementedCoreServer) SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedCoreServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedCoreServer) GetEstimatedTransactionFee(context.Context, *GetEstimatedTransactionFeeRequest) (*GetEstimatedTransactionFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEstimatedTransactionFee not implemented")
}
func (*UnimplementedCoreServer) SubscribeToBlockHeadersWithChainLocks(*BlockHeadersWithChainLocksRequest, Core_SubscribeToBlockHeadersWithChainLocksServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToBlockHeadersWithChainLocks not implemented")
}

func RegisterCoreServer(s *grpc.Server, srv CoreServer) {
	s.RegisterService(&_Core_serviceDesc, srv)
}

func _Core_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Core/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Core/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Core/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Core/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetEstimatedTransactionFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEstimatedTransactionFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetEstimatedTransactionFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Core/GetEstimatedTransactionFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetEstimatedTransactionFee(ctx, req.(*GetEstimatedTransactionFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_SubscribeToBlockHeadersWithChainLocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockHeadersWithChainLocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).SubscribeToBlockHeadersWithChainLocks(m, &coreSubscribeToBlockHeadersWithChainLocksServer{stream})
}

type Core_SubscribeToBlockHeadersWithChainLocksServer interface {
	Send(*BlockHeadersWithChainLocksResponse) error
	grpc.ServerStream
}

type coreSubscribeToBlockHeadersWithChainLocksServer struct {
	grpc.ServerStream
}

func (x *coreSubscribeToBlockHeadersWithChainLocksServer) Send(m *BlockHeadersWithChainLocksResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Core_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.dash.platform.dapi.v0.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStatus",
			Handler:    _Core_GetStatus_Handler,
		},
		{
			MethodName: "getBlock",
			Handler:    _Core_GetBlock_Handler,
		},
		{
			MethodName: "sendTransaction",
			Handler:    _Core_SendTransaction_Handler,
		},
		{
			MethodName: "getTransaction",
			Handler:    _Core_GetTransaction_Handler,
		},
		{
			MethodName: "getEstimatedTransactionFee",
			Handler:    _Core_GetEstimatedTransactionFee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribeToBlockHeadersWithChainLocks",
			Handler:       _Core_SubscribeToBlockHeadersWithChainLocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/protos/core.proto",
}
