// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        (unknown)
// source: grpc/protos/platform.proto

package org_dash_platform_dapi_v0

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ApplyStateTransitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateTransition []byte `protobuf:"bytes,1,opt,name=state_transition,json=stateTransition,proto3" json:"state_transition,omitempty"`
}

func (x *ApplyStateTransitionRequest) Reset() {
	*x = ApplyStateTransitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyStateTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyStateTransitionRequest) ProtoMessage() {}

func (x *ApplyStateTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyStateTransitionRequest.ProtoReflect.Descriptor instead.
func (*ApplyStateTransitionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyStateTransitionRequest) GetStateTransition() []byte {
	if x != nil {
		return x.StateTransition
	}
	return nil
}

type ApplyStateTransitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyStateTransitionResponse) Reset() {
	*x = ApplyStateTransitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyStateTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyStateTransitionResponse) ProtoMessage() {}

func (x *ApplyStateTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyStateTransitionResponse.ProtoReflect.Descriptor instead.
func (*ApplyStateTransitionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{1}
}

type GetIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetIdentityRequest) Reset() {
	*x = GetIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityRequest) ProtoMessage() {}

func (x *GetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{2}
}

func (x *GetIdentityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity []byte `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *GetIdentityResponse) Reset() {
	*x = GetIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityResponse) ProtoMessage() {}

func (x *GetIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{3}
}

func (x *GetIdentityResponse) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetDataContractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDataContractRequest) Reset() {
	*x = GetDataContractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataContractRequest) ProtoMessage() {}

func (x *GetDataContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataContractRequest.ProtoReflect.Descriptor instead.
func (*GetDataContractRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{4}
}

func (x *GetDataContractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDataContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataContract []byte `protobuf:"bytes,1,opt,name=data_contract,json=dataContract,proto3" json:"data_contract,omitempty"`
}

func (x *GetDataContractResponse) Reset() {
	*x = GetDataContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataContractResponse) ProtoMessage() {}

func (x *GetDataContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataContractResponse.ProtoReflect.Descriptor instead.
func (*GetDataContractResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataContractResponse) GetDataContract() []byte {
	if x != nil {
		return x.DataContract
	}
	return nil
}

type GetDocumentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataContractId string `protobuf:"bytes,1,opt,name=data_contract_id,json=dataContractId,proto3" json:"data_contract_id,omitempty"`
	DocumentType   string `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	Where          []byte `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	OrderBy        []byte `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Limit          uint32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Types that are assignable to Start:
	//	*GetDocumentsRequest_StartAfter
	//	*GetDocumentsRequest_StartAt
	Start isGetDocumentsRequest_Start `protobuf_oneof:"start"`
}

func (x *GetDocumentsRequest) Reset() {
	*x = GetDocumentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentsRequest) ProtoMessage() {}

func (x *GetDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{6}
}

func (x *GetDocumentsRequest) GetDataContractId() string {
	if x != nil {
		return x.DataContractId
	}
	return ""
}

func (x *GetDocumentsRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *GetDocumentsRequest) GetWhere() []byte {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *GetDocumentsRequest) GetOrderBy() []byte {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *GetDocumentsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (m *GetDocumentsRequest) GetStart() isGetDocumentsRequest_Start {
	if m != nil {
		return m.Start
	}
	return nil
}

func (x *GetDocumentsRequest) GetStartAfter() uint32 {
	if x, ok := x.GetStart().(*GetDocumentsRequest_StartAfter); ok {
		return x.StartAfter
	}
	return 0
}

func (x *GetDocumentsRequest) GetStartAt() uint32 {
	if x, ok := x.GetStart().(*GetDocumentsRequest_StartAt); ok {
		return x.StartAt
	}
	return 0
}

type isGetDocumentsRequest_Start interface {
	isGetDocumentsRequest_Start()
}

type GetDocumentsRequest_StartAfter struct {
	StartAfter uint32 `protobuf:"varint,6,opt,name=start_after,json=startAfter,proto3,oneof"`
}

type GetDocumentsRequest_StartAt struct {
	StartAt uint32 `protobuf:"varint,7,opt,name=start_at,json=startAt,proto3,oneof"`
}

func (*GetDocumentsRequest_StartAfter) isGetDocumentsRequest_Start() {}

func (*GetDocumentsRequest_StartAt) isGetDocumentsRequest_Start() {}

type GetDocumentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents [][]byte `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *GetDocumentsResponse) Reset() {
	*x = GetDocumentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_platform_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentsResponse) ProtoMessage() {}

func (x *GetDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_platform_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_platform_proto_rawDescGZIP(), []int{7}
}

func (x *GetDocumentsResponse) GetDocuments() [][]byte {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_grpc_protos_platform_proto protoreflect.FileDescriptor

var file_grpc_protos_platform_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6f, 0x72,
	0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x22, 0x48, 0x0a, 0x1b, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x22, 0xf4, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x68, 0x65, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x41, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x34, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0xed, 0x03, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x87,
	0x01, 0x0a, 0x14, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x37, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2d, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73,
	0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6f, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x2e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x64, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_protos_platform_proto_rawDescOnce sync.Once
	file_grpc_protos_platform_proto_rawDescData = file_grpc_protos_platform_proto_rawDesc
)

func file_grpc_protos_platform_proto_rawDescGZIP() []byte {
	file_grpc_protos_platform_proto_rawDescOnce.Do(func() {
		file_grpc_protos_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_protos_platform_proto_rawDescData)
	})
	return file_grpc_protos_platform_proto_rawDescData
}

var file_grpc_protos_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_protos_platform_proto_goTypes = []interface{}{
	(*ApplyStateTransitionRequest)(nil),  // 0: org.dash.platform.dapi.v0.ApplyStateTransitionRequest
	(*ApplyStateTransitionResponse)(nil), // 1: org.dash.platform.dapi.v0.ApplyStateTransitionResponse
	(*GetIdentityRequest)(nil),           // 2: org.dash.platform.dapi.v0.GetIdentityRequest
	(*GetIdentityResponse)(nil),          // 3: org.dash.platform.dapi.v0.GetIdentityResponse
	(*GetDataContractRequest)(nil),       // 4: org.dash.platform.dapi.v0.GetDataContractRequest
	(*GetDataContractResponse)(nil),      // 5: org.dash.platform.dapi.v0.GetDataContractResponse
	(*GetDocumentsRequest)(nil),          // 6: org.dash.platform.dapi.v0.GetDocumentsRequest
	(*GetDocumentsResponse)(nil),         // 7: org.dash.platform.dapi.v0.GetDocumentsResponse
}
var file_grpc_protos_platform_proto_depIdxs = []int32{
	0, // 0: org.dash.platform.dapi.v0.Platform.applyStateTransition:input_type -> org.dash.platform.dapi.v0.ApplyStateTransitionRequest
	2, // 1: org.dash.platform.dapi.v0.Platform.getIdentity:input_type -> org.dash.platform.dapi.v0.GetIdentityRequest
	4, // 2: org.dash.platform.dapi.v0.Platform.getDataContract:input_type -> org.dash.platform.dapi.v0.GetDataContractRequest
	6, // 3: org.dash.platform.dapi.v0.Platform.getDocuments:input_type -> org.dash.platform.dapi.v0.GetDocumentsRequest
	1, // 4: org.dash.platform.dapi.v0.Platform.applyStateTransition:output_type -> org.dash.platform.dapi.v0.ApplyStateTransitionResponse
	3, // 5: org.dash.platform.dapi.v0.Platform.getIdentity:output_type -> org.dash.platform.dapi.v0.GetIdentityResponse
	5, // 6: org.dash.platform.dapi.v0.Platform.getDataContract:output_type -> org.dash.platform.dapi.v0.GetDataContractResponse
	7, // 7: org.dash.platform.dapi.v0.Platform.getDocuments:output_type -> org.dash.platform.dapi.v0.GetDocumentsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_protos_platform_proto_init() }
func file_grpc_protos_platform_proto_init() {
	if File_grpc_protos_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_protos_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyStateTransitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyStateTransitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataContractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_platform_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDocumentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_protos_platform_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetDocumentsRequest_StartAfter)(nil),
		(*GetDocumentsRequest_StartAt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_protos_platform_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protos_platform_proto_goTypes,
		DependencyIndexes: file_grpc_protos_platform_proto_depIdxs,
		MessageInfos:      file_grpc_protos_platform_proto_msgTypes,
	}.Build()
	File_grpc_protos_platform_proto = out.File
	file_grpc_protos_platform_proto_rawDesc = nil
	file_grpc_protos_platform_proto_goTypes = nil
	file_grpc_protos_platform_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformClient interface {
	ApplyStateTransition(ctx context.Context, in *ApplyStateTransitionRequest, opts ...grpc.CallOption) (*ApplyStateTransitionResponse, error)
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error)
	GetDataContract(ctx context.Context, in *GetDataContractRequest, opts ...grpc.CallOption) (*GetDataContractResponse, error)
	GetDocuments(ctx context.Context, in *GetDocumentsRequest, opts ...grpc.CallOption) (*GetDocumentsResponse, error)
}

type platformClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformClient(cc grpc.ClientConnInterface) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) ApplyStateTransition(ctx context.Context, in *ApplyStateTransitionRequest, opts ...grpc.CallOption) (*ApplyStateTransitionResponse, error) {
	out := new(ApplyStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Platform/applyStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error) {
	out := new(GetIdentityResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Platform/getIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetDataContract(ctx context.Context, in *GetDataContractRequest, opts ...grpc.CallOption) (*GetDataContractResponse, error) {
	out := new(GetDataContractResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Platform/getDataContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) GetDocuments(ctx context.Context, in *GetDocumentsRequest, opts ...grpc.CallOption) (*GetDocumentsResponse, error) {
	out := new(GetDocumentsResponse)
	err := c.cc.Invoke(ctx, "/org.dash.platform.dapi.v0.Platform/getDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
type PlatformServer interface {
	ApplyStateTransition(context.Context, *ApplyStateTransitionRequest) (*ApplyStateTransitionResponse, error)
	GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error)
	GetDataContract(context.Context, *GetDataContractRequest) (*GetDataContractResponse, error)
	GetDocuments(context.Context, *GetDocumentsRequest) (*GetDocumentsResponse, error)
}

// UnimplementedPlatformServer can be embedded to have forward compatible implementations.
type UnimplementedPlatformServer struct {
}

func (*UnimplementedPlatformServer) ApplyStateTransition(context.Context, *ApplyStateTransitionRequest) (*ApplyStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyStateTransition not implemented")
}
func (*UnimplementedPlatformServer) GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (*UnimplementedPlatformServer) GetDataContract(context.Context, *GetDataContractRequest) (*GetDataContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataContract not implemented")
}
func (*UnimplementedPlatformServer) GetDocuments(context.Context, *GetDocumentsRequest) (*GetDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocuments not implemented")
}

func RegisterPlatformServer(s *grpc.Server, srv PlatformServer) {
	s.RegisterService(&_Platform_serviceDesc, srv)
}

func _Platform_ApplyStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).ApplyStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Platform/ApplyStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).ApplyStateTransition(ctx, req.(*ApplyStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Platform/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetDataContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetDataContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Platform/GetDataContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetDataContract(ctx, req.(*GetDataContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_GetDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).GetDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.dash.platform.dapi.v0.Platform/GetDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).GetDocuments(ctx, req.(*GetDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Platform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.dash.platform.dapi.v0.Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "applyStateTransition",
			Handler:    _Platform_ApplyStateTransition_Handler,
		},
		{
			MethodName: "getIdentity",
			Handler:    _Platform_GetIdentity_Handler,
		},
		{
			MethodName: "getDataContract",
			Handler:    _Platform_GetDataContract_Handler,
		},
		{
			MethodName: "getDocuments",
			Handler:    _Platform_GetDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/protos/platform.proto",
}
